### ISSUE TITLE
Using behind proxy

### ISSUE THREAD

**Issue by coolhandfluke** [noopkat/ms-bing-speech-service#11]
How to make this work behind proxy, I tried this and doesn't seem to work.

**Comment by coolhandfluke** [comment]
Could you update the module with following changes using https-proxy-agent, I tried with these changes and it worked behind proxy.
1.) In _requestAccessToken function,
if ( process.env.https_proxy ) {
        postRequest.agent = new httpsProxyAgent( process.env.https_proxy );
}
2.) In _connectToWebsocket function,
const extraOptions = {};
    if ( process.env.https_proxy ) {
        extraOptions.agent = new httpsProxyAgent( process.env.https_proxy );
    }
client.connect(this.serviceUrl, null, null, wsOptions,extraOptions);

**Comment by noopkat** [comment]
Hi @coolhandfluke,

Thanks for opening this issue. Apologies for not responding.

Recently, there's been a new official version of a NodeJS supported SDK for the unified Microsoft Speech Services (formally Bing Speech Service). I'd recommend checking that out instead, if you still have need for a library such as this: https://github.com/Azure-Samples/cognitive-services-speech-sdk

Therefore I'll respectfully close this issue and will be deprecating / archive this repo 🙇‍♀ Thanks again for your contribution.
