### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by danreeves** [noopkat/ms-bing-speech-service#14]
node --version: v9.2.0
ms-bing-speech-service: 2.0.0

I'm probably doing something wrong, but when I try sending a Buffer the `JSON.parse` in `onMessage` is exploding because `message.body` is just `{`.

Example message:
```
{ 'x-requestid': '[an alpha num]',
  'content-type': 'application/json; charset=utf-8',
  path: 'turn.start',
  body: [String: '{'],
  '"context"': '{',
  '"servicetag"': '"[an alpha num]"' }
```

**Comment by noopkat** [comment]
ah shoot 🤨 thanks for reporting! 

It seems that the incoming message parser is imperfect, and it should not be failing on this. I have patchy internet at the airport right now so I'm having trouble replicating, but will write an extra test for `turn.start` message parsing and try to get it behaving properly.

**Comment by noopkat** [comment]
ok, I think I know what happened. I forgot to build the node entry file before publishing. All the same, I added some more robustness around the parser and tweaked my test message data to more accurately represent the line breaks on messages coming in from the websocket.

once the tests pass in CI I'll merge it and publish. Would love if you could then retest please :pray:

**Comment by noopkat** [comment]
🚢 🚢 🚢  just shipped the fix.

Please reopen if you still run into issues. Thanks for testing out the major release so soon!

![bitmoji](https://render.bitstrips.com/v2/cpanel/15f269e9-79ff-42f5-b6f8-df81e1cb3847-01e208eb-dd84-4f55-b40d-40123903eb89-v1.png?transparent=1&palette=1&width=246)

**Comment by danreeves** [comment]
Speedy response! 🚀

Looks like that fixed the issue, thanks!
