### ISSUE TITLE
Error 'connection failed' when upgrading from v1.3.3 to v2.0.1

### ISSUE THREAD

**Issue by e-compton** [noopkat/ms-bing-speech-service#18]
Hi,

I'm experiencing an odd error when upgrading this package to the newer v2.0.1.

`connection.start()` throws a socket error with reason `connection failed`, even though `this._options` has not changed and works in v1.3.3 (using `language`, `issueTokenUrl`, `serviceUrl` and `subscriptionKey`).

Code:
```
acquire(cb) {
    debug('Giving Connection');
    let connection = new speechClient(this._options);

    connection.start().then(() => process.nextTick(() => {
      cb(null, connection);
    })).catch(err => process.nextTick(() => cb(err)));
  }
```
Full error:
```
 speechService socket error: _Event {
  type: 'error',
  isTrusted: false,
  _yaeti: true,
  target: 
   W3CWebSocket {
     _listeners: {},
     addEventListener: [Function: _addEventListener],
     removeEventListener: [Function: _removeEventListener],
     dispatchEvent: [Function: _dispatchEvent],
     _url: '<removed for security reasons>',
     _readyState: 3,
     _protocol: undefined,
     _extensions: '',
     _bufferedAmount: 0,
     _binaryType: 'arraybuffer',
     _connection: undefined,
     _client: 
      WebSocketClient {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        config: [Object],
        _req: null,
        protocols: [],
        origin: undefined,
        url: [Object],
        secure: true,
        base64nonce: '3JE7wIKvwWUGZhRMeVOpbQ==' },
     onmessage: [Function: bound onMessage],
     onerror: [Function],
     onclose: [Function],
     onopen: [Function] },
  cancelable: true,
  stopImmediatePropagation: [Function] } +51s
  speechService socket close: _Event {
  type: 'close',
  isTrusted: false,
  _yaeti: true,
  code: 1006,
  reason: 'connection failed',
  wasClean: false,
  target: 
   W3CWebSocket {
     _listeners: {},
     addEventListener: [Function: _addEventListener],
     removeEventListener: [Function: _removeEventListener],
     dispatchEvent: [Function: _dispatchEvent],
     _url: '<removed for security reasons>',
     _readyState: 3,
     _protocol: undefined,
     _extensions: '',
     _bufferedAmount: 0,
     _binaryType: 'arraybuffer',
     _connection: undefined,
     _client: 
      WebSocketClient {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        config: [Object],
        _req: null,
        protocols: [],
        origin: undefined,
        url: [Object],
        secure: true,
        base64nonce: '3JE7wIKvwWUGZhRMeVOpbQ==' },
     onmessage: [Function: bound onMessage],
     onerror: [Function],
     onclose: [Function],
     onopen: [Function] },
  cancelable: true,
  stopImmediatePropagation: [Function] }
```

**Comment by noopkat** [comment]
Hi @e-compton, thanks for reporting this issue. Sorry that you're having troubles upgrading this package in your codebase.


Could you please try running your code again, with `DEBUG=speechService` set as an environment variable? eg. `DEBUG=speechService node myfile.js`

Feel free to sanitize anything you need to in the output, before pasting it in here.

Thanks in advance for the help!
![bitmoji](https://render.bitstrips.com/v2/cpanel/214e2e2c-3a98-46f6-9b61-50c57a0d8fca-01e208eb-dd84-4f55-b40d-40123903eb89-v1.png?transparent=1&palette=1&width=246)

**Comment by noopkat** [comment]
update - Looks like you were using a custom speech service endpoint? I've issued a patch that I've manually tested on my end. Could you please retest your migration code with v2.0.2 which has the patch in it? Thanks!

**Comment by e-compton** [comment]
Yes, I am using a custom speech endpoint.

The new patch v2.0.2 works perfectly thank you :)

**Comment by noopkat** [comment]
great to hear! Thanks for your help again and I'm glad we could get you unstuck. Closing this issue.

![bitmoji](https://render.bitstrips.com/v2/cpanel/26530caf-ab1e-4400-9f3b-67155dd70751-01e208eb-dd84-4f55-b40d-40123903eb89-v1.png?transparent=1&palette=1&width=246)
