### ISSUE TITLE
Issue with custom speech API sample code

### ISSUE THREAD

**Issue by RawStewage** [noopkat/ms-bing-speech-service#24]
Hi, so I was just working with your sample code for the custom speech service and for some reason the service hangs after the first transcription. It appears that the `turn.end` event is never fired and thus the client just sits after the first pass. 

Have you seen this issue before? Could there be something I'm doing wrong? 

Thanks in advance for any help

**Comment by noopkat** [comment]
HI @RawStewage thanks for reporting this. Quite puzzling. I highly doubt you're doing anything wrong!

I'll run the sample on my end and see if I can reproduce and we can go from there. Sorry about the trouble!

![bitmoji](https://render.bitstrips.com/v2/cpanel/9d438724-a1e5-44b9-9172-377503bbffe6-bb1d1734-97c2-47a8-b8d9-ea2fd776060f-v1.png?transparent=1&palette=1&width=246)

**Comment by noopkat** [comment]
@RawStewage hey there - just letting you know that after testing on my end, @pvaillant's PR #25 fixes this issue. Let me know if you see any more bugs and thanks for reporting this one!
