### ISSUE TITLE
document new access token option

### ISSUE THREAD

**Issue by noopkat** [noopkat/ms-bing-speech-service#8]
A new feature was added recently to allow an access token for authorisation, instead of using a subscription key (see #7). 

Documenting this new configuration option in the README would be wonderful if anyone would like to take this issue. It would involve a new section about authorisation explaining the two ways to auth, as well as the options table needing an addition.

**Comment by filljoyner** [comment]
I can update readme late this evening.

**Comment by noopkat** [comment]
closing as @filljoyner fixed this via #10
